version: "3.9"
services:
  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: todo-backend
    #volumes:
    #  - ./backend/src:/app/src
    #  - ./backend/target:/app/target
    #command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tododb
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo123
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build: ./frontend
    container_name: todo-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8080/api
      # - NODE_ENV=production
    ports:
      - "3000:80"

volumes:
  db_data: